# Generated by Django 5.1.1 on 2025-01-07 16:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='osoba', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('osoba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='journal_app.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motyw_kolor', models.CharField(choices=[('light', 'Jasny'), ('dark', 'Ciemny')], default='light', max_length=10)),
                ('osoba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ustawienia', to='journal_app.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('tresc', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_aktualizacji', models.DateTimeField(auto_now=True)),
                ('upl_img', models.ImageField(null=True, upload_to='imgs_uploaded')),
                ('upl_mov', models.FileField(null=True, upload_to='vids_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy', to='journal_app.osoba')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
