# Generated by Django 5.1.5 on 2025-01-20 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_osoba_profil_ustawienia_wpis_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_other_person', 'Moze zobaczyc osoby innych włascicieli')], 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterField(
            model_name='wpis',
            name='upl_img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs_uploaded'),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='upl_mov',
            field=models.FileField(blank=True, null=True, upload_to='vids_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
