# Generated by Django 5.1.1 on 2025-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_alter_osoba_options_alter_wpis_upl_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpis',
            name='upl_mov',
        ),
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
